### PR TITLE
Ignore actual log dir instead of non-existent logs

### PR DESCRIPTION
**Pull request by alsemyonov**

### CODE REVIEW

**Comment by andriytyurnikov** [comment]
please consider merge of #24 instead

**Comment by alsemyonov** [comment]
Any consistent solution would be better than confusing one right now.

**Comment by timriley** [comment]
Thanks for your PRs here, I'll try get something merged in the next week.

**Comment by timriley** [comment]
Thanks @alsemyonov, pulled this one in and will release shortly.

**Pull request merged**
