### PR TITLE
Update roda version

### PR DESCRIPTION
**Pull request by GustavoCaso**
#81 

This PR update `roda` version to be compatible with the latest version of `roda-flow`, which is updated to work with the latest version of `roda` to avoid having issues with the routing wildcard
[forum](https://discourse.dry-rb.org/t/dry-web-roda-roda-flow-plugin-causing-routing-wildcard/461)
https://github.com/AMHOL/roda-flow/commit/f3f00bff0e07525a1cda59e5a29f61e71795e7cf
https://github.com/jeremyevans/roda/blob/3.4.0/lib/roda.rb#L836

I have talked with @alejandrobabio who have a couple of apps so we can test the change and make sure everything still working

### CODE REVIEW

**Comment by alejandrobabio** [comment]
Hi @gustavocaso, I was investigating this issue.

[This](https://github.com/AMHOL/roda-flow/commit/f3f00bff0e07525a1cda59e5a29f61e71795e7cf#diff-58d4733fa4db8450ba32d215214d3d46R24) roda-flow change is the one that broke things in dry-web-roda, but it is correct. The previous `if_match` method, converted the argument in an array and changed the way that roda routes the paths (as it was reported).

The fix is quite easy: changing the `is` call with an `on` call in [dry-view](https://github.com/dry-rb/dry-web-roda/blob/master/lib/roda/plugins/dry_view.rb#L25). I think this change is correct and safe because at the moment of call `r.view` all the routing process was done, so the call is only for processing not for routing. Anyway, I'm open to other possibilities or better ways to fix the issue.

I verified it in my app:
1. The issue was only with the root path (because it expects that the remaining path to be "" and it is "/")
2. Invalid path still returns 404 page
3. The app works as expected
4. All my tests are still passing

**Comment by GustavoCaso** [comment]
@alejandrobabio thank you so much for taking the time to investigate it.

I have looked `roda` implementation of [on](https://github.com/jeremyevans/roda/blob/3.4.0/lib/roda.rb#L505) and [is](https://github.com/jeremyevans/roda/blob/3.4.0/lib/roda.rb#L460) I think also is a safe change. I will update the PR and if you want to test on your apps will be great

**Comment by alejandrobabio** [comment]
I did, changing `is` with `on`. It works fine. All the tests are finished ok. And the app too.

**Comment by GustavoCaso** [comment]
@timriley I think we are safe to merge this one and be up to date with `roda` and `roda-flow` I would like to thank @alejandrobabio for taking the time to investigate and find a solution to our problem.

@alejandrobabio thank you so much ❤️ 👏

**Comment by alejandrobabio** [comment]
No problem. It was a good opportunity to read and learn about all these gems.

**Comment by abrthel** [comment]
A new version push would be much appreciated. Right now, routes such as:

```ruby
r.is 'province', String do |province_id|
end
```

are being interpreted as an or matcher so `/foo` & `/province/foo` are both valid paths when it should just be `/province/foo`

To workaround an explicit all matcher is required

```ruby
r.is all: ['province', String] do |province_id|
end
```

**Comment by timriley** [comment]
Thanks for the PR and feedback, folks. I'm going to merge this now and then bump our roda-flow dependency version spec to `~> 0.4`, since that seems to be the one with the adjustments for the latest roda.

**Comment by timriley** [comment]
FYI, just released 0.11.0, which uses the latest roda and roda-flow.

**Pull request merged**
