### PR TITLE
[WIP] Adapt to dry-view 1.0

### PR DESCRIPTION
**Pull request by waiting-for-dev**
This can be used as starting point to adapt the project when `dry-view` 1.0 is released.

References AMHOL/roda-flow#5, which would also need a fix.

### CODE REVIEW

**Comment by waiting-for-dev** [comment]
One option is also to add `erbse` to the Gemfile with a notice about it could be safely removed if `erb` format is not used with `dry-view`. However, `dry-view` warning is quite explicit in that case.

**Comment by bricesanchez** [comment]
Hi @waiting-for-dev, Do you have any news about this PR, it helps me to fix some issues but i'm struggled with the render of the view?

**Comment by waiting-for-dev** [comment]
I'm not sure it will get more attention because `dry-web-roda` will be abandoned in favor of `hanami 2`. That being said, `dry-web-roda` is not much more than a bunch of small libraries working together, so our code won't need too much change to still rely on actively developed libraries. You can ask me whatever you need in [dry-rb discussion forums](https://discourse.dry-rb.org/).

**Comment by waiting-for-dev** [comment]
I guess this can be closed in favor of #94

**Pull request closed without merging**
