### PR TITLE
Add multiple verbs in web generators

### PR DESCRIPTION
**Pull request by waiting-for-dev**
I think it is a sensible default for modern REST applications. Don't you agree?

### CODE REVIEW

**Comment by gotar** [comment]
depend I'm using it now to write GraphQL API, and only endpoint I need is single POST

**Comment by waiting-for-dev** [comment]
Hmm... true... But looking at what is already present in the generators, I think `dry-web-roda` tries to create a common use case configuration from where you can remove elements, instead of a minimal configuration from which you can build upon.

For example, `Rack::Sessions` is enabled even if it will be removed in a lot of cases.

**Comment by parndt** [comment]
I'd be in favour of this. As someone new to it, I was pretty confused why PUT/PATCH weren't working :wink:

**Comment by timriley** [comment]
Thanks @waiting-for-dev :)

**Pull request merged**
